"""cached and processing time

Revision ID: 67ed68c2d07f
Revises: b598f2a925ed
Create Date: 2026-04-07 05:57:52.975211

"""

from alembic import op
import sqlalchemy as sa



revision = '67ed68c2d07f'
down_revision = 'b598f2a925ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cached', sa.Boolean(), nullable=False))
    op.add_column('jobs', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'processing_time_ms')
    op.drop_column('jobs', 'cached')
    # ### end Alembic commands ###

